<CreateProgramScreen>:
    name: "create_program"
    BoxLayout:
        orientation: 'vertical'
        padding: '10dp'
        spacing: '10dp'
        MDTextFieldLettersNumsSpacing:
            id: program_name
            input_filter: self.insert_filter
            required: True
            helper_text: "Введіть назву"
            max_text_length: 30
            hint_text: "Назва програми"
            mode: "rectangle"
        ScrollView:
            MDList:
                id: muscle_groups_list
        MDRaisedButton:
            text: "Зберегти програму"
            pos_hint: {'center_x': 0.5}
            on_release: root.save_program()